jetson-tx2-4gb: Add balena support for TX2 variant.
balena-os/balena-jetson pull request #177
Opened 2021-05-28 18:56 UTC by smithandrewc

2021-05-31 08:34 UTC, acostach requested changes
Hi @smithandrewc and thank you for your PR.

Can you please add a "Changelog-entry" and "Signed-off-by:" to your commit message, and also have a look at the comments I left. We can avoid duplicating the tx2 sources and recipe code by extending the existing jetson-tx2 machine and overriding only what is specific.

2021-05-31 08:34 UTC, acostach commented on layers/meta-balena-jetson/recipes-bsp/tegra-binaries/tegra186-flash-dry_32.4.4.bb
> +do_configure_jetson-tx2-4gb() {
this wouldn't be necessary anymore when using the same partition spec and xml

2021-05-31 08:34 UTC, acostach commented on layers/meta-balena-jetson/recipes-bsp/tegra-binaries/tegra186-flash-dry_32.4.4.bb
> +do_install_jetson-tx2-4gb() {
This one could be removed completely with the changes suggested above.

2021-05-31 08:34 UTC, acostach commented on layers/meta-balena-jetson/recipes-bsp/u-boot/u-boot-tegra_%.bbappend
> +BALENA_BOOT_PART_jetson-tx2-4gb = "0x18"
These ones would be applied to the 4gb too when in extending the tx2

2021-05-31 08:34 UTC, acostach commented on layers/meta-balena-jetson/recipes-bsp/u-boot/u-boot-tegra_%.bbappend
> +SRC_URI_append_jetson-tx2-4gb = " \
These ones can be dropped when extending the jetson-tx2.conf machine since it's the same u-boot version and same machine defconfig

2021-05-31 08:34 UTC, acostach commented on layers/meta-balena-jetson/recipes-core/images/balena-image-flasher.bbappend
Changes in this file could be dropped

2021-05-31 08:34 UTC, acostach commented on layers/meta-balena-jetson/recipes-bsp/u-boot/u-boot-tegra_%.bbappend
> +TEGRA_BOARD_FDT_FILE_jetson-tx2-4gb="tegra186-quill-p3489-0888-a00-00-base.dtb"
This is ok since it's 4gb specific.

2021-05-31 08:34 UTC, acostach commented on layers/meta-balena-jetson/recipes-core/images/balena-image-initramfs.bbappend
> +PACKAGE_INSTALL_append_jetson-tx2-4gb = " kernel-module-bcmdhd"
Can be dropped when extending the tx2 machine

2021-05-31 08:34 UTC, acostach commented on layers/meta-balena-jetson/recipes-core/images/balena-image.bbappend
> +    partitions=$(cat ${DEPLOY_DIR_IMAGE}/tegra-binaries/partition_specification186.txt)
Works with the existing partition_specification186.txt

2021-05-31 08:34 UTC, acostach commented on layers/meta-balena-jetson/recipes-core/images/balena-image.inc
> +do_rootfs_balenaos-img_jetson-tx2-4gb[depends] += " tegra186-flash-dry:do_deploy \
Can be dropped when extending the tx2 yocto machine

2021-05-31 08:34 UTC, acostach commented on layers/meta-balena-jetson/recipes-core/images/balena-image.inc
> +BALENA_BOOT_PARTITION_FILES_jetson-tx2-4gb = " \
Same here

2021-05-31 08:34 UTC, acostach commented on layers/meta-balena-jetson/recipes-core/images/balena-image.inc
> +BALENA_BOOT_SIZE_jetson-tx2-4gb="80960"
Same

2021-05-31 08:34 UTC, acostach commented on layers/meta-balena-jetson/recipes-core/images/balena-image.inc
> +IMAGE_INSTALL_append_jetson-tx2-4gb = " \
Same here

2021-05-31 08:34 UTC, acostach commented on layers/meta-balena-jetson/recipes-core/packagegroups/packagegroup-resin-connectivity.bbappend
> +CONNECTIVITY_FIRMWARES_append_jetson-tx2-4gb = " \
Same, dropped

2021-05-31 08:34 UTC, acostach commented on layers/meta-balena-jetson/recipes-kernel/linux-firmware/linux-firmware_%.bbappend
> +SRCREV_jetson-tx2-4gb = "0dd245d3691f99c87be5d0373625960e545b6493"
Same, all changes in this file can be dropped

2021-05-31 08:34 UTC, acostach commented on layers/meta-balena-jetson/recipes-kernel/linux/jetson-dtbs.bb
> +	install -m 0644 ${DEPLOY_DIR_IMAGE}/tegra186-quill-p3489-0888-a00-00-base.dtb ${D}/boot/tegra186-quill-p3489-0888-a00-00-base.dtb
Only tegra186-quill-p3489-0888-a00-00-base.dtb is necessary when extending the existing machine, for instance:

```
do_install_append_tx2-4gb() {
    install -m 0644 ${DEPLOY_DIR_IMAGE}/tegra186-quill-p3489-0888-a00-00-base.dtb ${D}/boot/tegra186-quill-p3489-0888-a00-00-base.dtb
}
```

2021-05-31 08:34 UTC, acostach commented on layers/meta-balena-jetson/recipes-kernel/linux/jetson-dtbs.bb
> +	/boot/tegra186-quill-p3489-0888-a00-00-base.dtb \
Same as above, only the specific dtb needed

2021-05-31 08:34 UTC, acostach commented on layers/meta-balena-jetson/recipes-kernel/linux/linux-tegra_%.bbappend
> +SRC_URI_append_jetson-tx2-4gb = " \
Same, all changes in this file can be dropped

2021-05-31 08:34 UTC, acostach commented on layers/meta-balena-jetson/recipes-kernel/linux/linux-tegra_%.bbappend
> +BALENA_CONFIGS_append_jetson-tx2-4gb = " tpg eqos_disable_eee"
Same, can be dropped

2021-05-31 08:34 UTC, acostach commented on layers/meta-balena-jetson/recipes-support/hostapp-update-hooks/hostapp-update-hooks.bbappend
> +DEPENDS_append_jetson-tx2-4gb = " tegra186-flash-dry"
All changes in this file can be dropped when inheriting

2021-05-31 08:34 UTC, acostach commented on layers/meta-balena-jetson/recipes-support/resin-info/resin-info.bbappend
>  TTYS_jetson-xavier-nx-devkit-emmc=" ttyTHS0 tty1"
Same here

2021-05-31 08:34 UTC, acostach commented on layers/meta-balena-jetson/recipes-support/resin-init/resin-init-flasher.bbappend
>  INTERNAL_DEVICE_KERNEL_jetson-tx2 = "mmcblk0"
And here

2021-05-31 13:54 UTC, smithandrewc commented on layers/meta-balena-jetson/recipes-bsp/tegra-binaries/files/partition_specification186-4gb.txt
> +mts-bootpack:mce_mts_d15_prod_cr_sigheader.bin.encrypt:8192
No this file is slightly different

bpmp-fw-dtb and bpmp-fw-dtb_b lines are different.

2021-05-31 13:55 UTC, smithandrewc commented on layers/meta-balena-jetson/conf/layer.conf
> +SERIAL_CONSOLES_jetson-tx2-4gb = "115200;ttyS0"
Ok I'll see what I can do to clean it up.

2021-05-31 20:35 UTC, smithandrewc commented
I just pushed a new commit, most of which changes over the common jetson-tx2 code to use the tegra186 platform.  I couldn't make it work using jetson-tx2-4gb with a MACHINEOVERRIDES with jetson-tx2.  I think the issue is that jetson-tx2 is a machine itself, so overriding jetson-tx2-4gb causes conflicts when building some of the code.  I believe using tegra186 is what's done in the meta-tegra layer.  Making this switch will hopefully help when it comes time to add the TX2 NX.

2021-06-03 11:01 UTC, acostach commented
Thanks @smithandrewc , indeed, masking the upstream meta-tegra 4gb variant doesn't seem to work. I tried another approach by creating a jetson-tx2-4-gb slug which overrides the files you mentioned to be different and it appears to at least generate image partitions as expected. Can you try a local build of https://github.com/balena-os/balena-jetson/pull/180 and see if it boots or needs other changes?

2021-08-12 10:31 UTC, acostach commented
@smithandrewc so we've now merged all changes for 32.5.1 and released the TX2 NX image. We also have the tx2-4gb community device, but it needs updated boot blobs from your side, this time for L4T 32.5.1. We can then release the image in the dashboard. Thanks

2021-08-13 14:56 UTC, smithandrewc commented
> @smithandrewc so we've now merged all changes for 32.5.1 and released the TX2 NX image. We also have the tx2-4gb community device, but it needs updated boot blobs from your side, this time for L4T 32.5.1. We can then release the image in the dashboard. Thanks

Thanks, I'll get on this as soon as I can.

2021-10-13 06:36 UTC, acostach commented
@smithandrewc please see my previous comment:

> it needs updated boot blobs from your side, this time for L4T 32.5.1. We can then release the image in the dashboard.

This device-type is currently not available in the dashboard because we're waiting for updated boot binaries on L4T 32.5.1 from you. If we can't get it in the dashboard, we'll need to clean it up to avoid confusion for users.

2022-02-16 08:18 UTC, acostach commented
No update received for this DT, so no image unfortunately cannot be released to the dashboard. Please open a new PR on 32.6.1 if still needed.

2022-02-16 08:18 UTC, closed without merging